/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BaiThucHanh1.Bai8;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HomeFrm extends javax.swing.JFrame {

    private ArrayList<Word> listWord;
    private final DefaultTableModel model;
    

    /**
     *
     * Creates new form HomeFrm
     */
    public HomeFrm() {
        
        listWord = new ArrayList<>();
        initWord();
        initComponents();
        jPanelResult.setVisible(false);
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) tblXuat.getModel();
    }

    public void initWord() {
        listWord.add(new Word("1", "Hello", "xin chao"));
        listWord.add(new Word("2", "Array", "mang"));
        listWord.add(new Word("3", "apple", "tao"));
        listWord.add(new Word("4", "any", "bat ky"));
        listWord.add(new Word("5", "book", "sach"));
        listWord.add(new Word("6", "center", "trung tam"));
        listWord.add(new Word("7", "dictionary", "tu dien"));
        listWord.add(new Word("8", "element", "phan tu"));
        listWord.add(new Word("9", "friend", "ban be"));
        listWord.add(new Word("10", "why", "tai sao"));
        listWord.add(new Word("11", "fire", "lửa"));
        Collections.sort(listWord);
        System.out.println(listWord.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtkeyWord = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jPanelResult = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXuat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Words");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Dictionary");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Result");

        tblXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "English", "Vietnamese"
            }
        ));
        jScrollPane1.setViewportView(tblXuat);

        javax.swing.GroupLayout jPanelResultLayout = new javax.swing.GroupLayout(jPanelResult);
        jPanelResult.setLayout(jPanelResultLayout);
        jPanelResultLayout.setHorizontalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(207, 207, 207))))
        );
        jPanelResultLayout.setVerticalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtkeyWord)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jPanelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addWord(Word w) {
        w.setId("" + (listWord.size() + 1));
        int index = FindIndexToAdd(listWord,0,listWord.size() - 1,w.getEn());
        System.out.println("add vao vi tri " +index);
        listWord.add(index,w);
    }
    //1 2 3 5 6 7 8 9
    public int FindIndexToAdd(ArrayList<Word> arr, int left, int right, String key) {
        key = key.toLowerCase();
        if (left > right) {
            
            return left;
            
        }
        int mid = (left + right) / 2;
        String arr_en = arr.get(mid).getEn().toLowerCase();
        if (arr.get(mid).getEn().toLowerCase().compareTo(key) == 0) {
            return mid;
        } else if (key.compareTo(arr_en) > 0) {
            left = mid + 1;

        } else if (key.compareTo(arr_en) < 0) {
            right = mid - 1;
        }
        return FindIndexToAdd(arr, left, right, key);

    }
    public int binarySearch(ArrayList<Word> arr, int left, int right, String key) {
        key = key.toLowerCase();
        if (left > right) {
            return -1;
        }
        int mid = (left + right) / 2;
        String arr_en = arr.get(mid).getEn().toLowerCase();
        if (arr.get(mid).getEn().toLowerCase().compareTo(key) == 0) {
            return mid;
        } else if (key.compareTo(arr_en) > 0) {
            left = mid + 1;

        } else if (key.compareTo(arr_en) < 0) {
            right = mid - 1;
        }
        return binarySearch(arr, left, right, key);

    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyWords = txtkeyWord.getText();
        keyWords = keyWords.toLowerCase();
        
        int index = binarySearch(listWord, 0, listWord.size() - 1, keyWords);

        if (index > -1) {
            model.setRowCount(0);
            model.addRow(listWord.get(index).toArrayStrings());
            jPanelResult.setVisible(true);

        }
        if (index == -1) { // ko tìm thấy

            int ans = JOptionPane.showConfirmDialog(this, "Không tìm thấy từ " + keyWords
                    + " trong từ điển\n Bạn có muốn thêm tử này vào từ điển không?");
            if (ans == 0) {
                AddWordFrm addWordFrm = new AddWordFrm(this, rootPaneCheckingEnabled);
                addWordFrm.setVisible(true);
                 model.setRowCount(0);
                 listWord.forEach(obj->{
                 model.addRow(obj.toArrayStrings());
                 });
                 ;
                 jPanelResult.setVisible(true);
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblXuat;
    private javax.swing.JTextField txtkeyWord;
    // End of variables declaration//GEN-END:variables
}
